package com.tivetechnology.apple_sign_in

class Constants {
    companion object {
        // Base
        val TAG = "FLTFirebaseAuthPlugin"
        val ANDROID = "android"
        val IOS = "iOS"
        val MINIMUM_VERSION = "minimumVersion"
        val INSTALL_APP = "installApp"
        val PACKAGE_NAME = "packageName"
        val BUNDLE_ID = "bundleId"
        val APP_NAME = "appName"

        // Providers
        val SIGN_IN_METHOD_PASSWORD = "password"
        val SIGN_IN_METHOD_EMAIL_LINK = "emailLink"
        val SIGN_IN_METHOD_FACEBOOK = "facebook.com"
        val SIGN_IN_METHOD_GOOGLE = "google.com"
        val SIGN_IN_METHOD_TWITTER = "twitter.com"
        val SIGN_IN_METHOD_GITHUB = "github.com"
        val SIGN_IN_METHOD_PHONE = "phone"
        val SIGN_IN_METHOD_OAUTH = "oauth"

        // User
        val USER = "user"
        val EMAIL = "email"
        val NEW_EMAIL = "newEmail"
        val UID = "uid"
        val USERNAME = "username"
        val PASSWORD = "password"
        val NEW_PASSWORD = "newPassword"
        val PREVIOUS_EMAIL = "previousEmail"
        val EMAIL_VERIFIED = "emailVerified"
        val IS_ANONYMOUS = "isAnonymous"
        val IS_NEW_USER = "isNewUser"
        val METADATA = "metadata"
        val DISPLAY_NAME = "displayName"
        val PHONE_NUMBER = "phoneNumber"
        val PHOTO_URL = "photoURL"
        val PROFILE = "profile"
        val ADDITIONAL_USER_INFO = "additionalUserInfo"
        val CREATION_TIME = "creationTime"
        val LAST_SIGN_IN_TIME = "lastSignInTime"
        val TENANT_ID = "tenantId"

        // Auth
        val PROVIDERS = "providers"
        val PROVIDER_ID = "providerId"
        val PROVIDER_DATA = "providerData"
        val AUTH_CREDENTIAL = "authCredential"
        val CREDENTIAL = "credential"
        val SECRET = "secret"
        val REFRESH_TOKEN = "refreshToken"
        val ID_TOKEN = "idToken"
        val TOKEN = "token"
        val ACCESS_TOKEN = "accessToken"
        val CODE = "code"
        val RAW_NONCE = "rawNonce"
        val EMAIL_LINK = "emailLink"
        val VERIFICATION_ID = "verificationId"
        val SMS_CODE = "smsCode"
        val URL = "url"
        val DYNAMIC_LINK_DOMAIN = "dynamicLinkDomain"
        val LANGUAGE_CODE = "languageCode"
        val CLAIMS = "claims"
        val TIMEOUT = "timeout"
        val AUTH_TIMESTAMP = "authTimestamp"
        val EXPIRATION_TIMESTAMP = "expirationTimestamp"
        val ISSUED_AT_TIMESTAMP = "issuedAtTimestamp"
        val SIGN_IN_METHOD = "signInMethod"
        val SIGN_IN_PROVIDER = "signInProvider"
        val SIGN_IN_PROVIDER_SCOPE = "scopes"
        val SIGN_IN_PROVIDER_CUSTOM_PARAMETERS = "customParameters"
        val SIGN_IN_SECOND_FACTOR = "signInSecondFactor"
        val FORCE_RESENDING_TOKEN = "forceResendingToken"
        val FORCE_REFRESH = "forceRefresh"
        val TOKEN_ONLY = "tokenOnly"
        val HANDLE_CODE_IN_APP = "handleCodeInApp"
        val ACTION_CODE_SETTINGS = "actionCodeSettings"
        val AUTO_RETRIEVED_SMS_CODE_FOR_TESTING = "autoRetrievedSmsCodeForTesting"
        val HOST = "host"
        val PORT = "port"
        val NAME = "name"
        val APP_VERIFICATION_DISABLED_FOR_TESTING = "appVerificationDisabledForTesting"
        val FORCE_RECAPTCHA_FLOW = "forceRecaptchaFlow"

        // MultiFactor
        val MULTI_FACTOR_HINTS = "multiFactorHints"
        val MULTI_FACTOR_SESSION_ID = "multiFactorSessionId"
        val MULTI_FACTOR_RESOLVER_ID = "multiFactorResolverId"
        val MULTI_FACTOR_INFO = "multiFactorInfo"
    }
}
